services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        app_env: development
    working_dir: /app
    ports:
      - "8090:8090"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .git
